### PR TITLE
Release 2.1.8

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-github/pull/718

### CODE REVIEW

**Review by avas27JTG — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Review by hanzei — CHANGES_REQUESTED** [review]
Are we sure that the notification issue @amyblais run into (https://community.mattermost.com/core/pl/eoye7unqrigjj8uitkgbr7bgow) isn't caused by the changes to the webhook?

**Comment by raghavaggarwal2308** [comment]
@hanzei Yes, the issue is not caused by the changes in this https://github.com/mattermost/mattermost-plugin-github/pull/718 PR. We have tested it as well.

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
I've confirmed the reopen feature works correctly:

CleanShot 2023-12-13 at 04 07 11

**Comment by AayushChaudhary0001** [comment]
Tested and approved, LGTM.

**Pull request merged**
