### PR TITLE
Fix cutoff words in word wrap

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

Updates css to fix cutoff words in word wrap.

#### Ticket Link

Fixes: #455

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Seems to work for me! Thanks @haardikdharma10

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@haardikdharma10 Thanks so much for fixing this! Looking forward to seeing this ship 🙂 

@DHaussermann Please see the linked ticket for discussion on this issue. The PR should be tested in several browsers to verify styling consistency.

**Review by hanzei — APPROVED** [review]
Nice :+1:

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed a `-` now shows that word is wrapping to the next line
- Regression tested other edge-cases with pop-up
- Added this case to GitHub release testing 
LGTM!

Thanks  @haardikdharma10 for the PR! Much appreciated.

**Pull request merged**
