### PR TITLE
Fix unconvert issues using golangci-lint

### PR DESCRIPTION
**Pull request by agnivade**

### CODE REVIEW

**Comment by hanzei** [comment]
@agnivade Would you be open on adding a golangci file to the repo so we can enforce these rules in the future?

**Comment by agnivade** [comment]
Will do :+1:

**Comment by ali-farooq0** [comment]
@agnivade just a gentle reminder to finish any outstanding work on this PR.

**Comment by agnivade** [comment]
I don't believe there is something pending from my side. I meant to add the golangci config in a separate PR, unless @hanzei meant for me to add it in this PR ?

**Comment by hanzei** [comment]
Yes, i meant adding the config file in a separate PR :+1:

**Pull request merged**
