### PR TITLE
Removed commented text in Tooltip link body

### PR DESCRIPTION
**Pull request by abdulsmapara**
#### Summary

- Removed commented text present in body of PR/Issue that was displayed in the tooltip (on hovering over PR/issue link) by using `mdCommentRegex`, prepared from the regex for 'comments in markdown' available in `template.go`[1].

[1] [https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/template.go#L13-L28](https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/template.go#L13-L28)

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-github/issues/312

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann This might be a good PR for dev QA testing.

**Comment by DHaussermann** [comment]
@larkox or @hanzei,  If you have a bit of time, could one of you peer-test this PR using the  peer testing process documented here https://mattermost.atlassian.net/wiki/spaces/INT/pages/619937892/Peer+Testing+Process

**Comment by hanzei** [comment]
@DHaussermann :point_up:

**Comment by hanzei** [comment]
This PR introduced a regression. If `Body` is empty i.e. `nil`, the two changed lines will `panic`. @abdulsmapara Would you be open on fixing this?

**Comment by abdulsmapara** [comment]
Nice edge case, I would like to fix the issue !

**Comment by hanzei** [comment]
Thanks @abdulsmapara :+1:

**Comment by abdulsmapara** [comment]
Should I open a new PR or is it possible to reopen this one itself @hanzei ?

**Comment by hanzei** [comment]
@abdulsmapara Could you please open a new PR for the fix? It's not possible to reopen this one

**Pull request merged**
