### PR TITLE
Bump version to 0.14.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Bump version to 0.14.0

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/195

### CODE REVIEW

**Comment by hanzei** [comment]
Let's wait a bit and get more changes in.

@jfrerich Do have an ETA for https://github.com/mattermost/mattermost-plugin-github/pull/123?

**Comment by jfrerich** [comment]
@hanzei, Give me about two days and I'll get the changes submitted as a PR for the author to merge.

**Comment by jfrerich** [comment]
@hanzei, @levb and I discussed https://github.com/mattermost/mattermost-plugin-github/pull/123 and agreed we should not hold up this bump, for that ticket.  Please move forward with the bump and we'll add the `create issue` modal in the future.

**Comment by hanzei** [comment]
@DHaussermann Finally this is ready for review

**Pull request merged**
