### PR TITLE
MM-17864 - Updating github items css

### PR DESCRIPTION
**Pull request by asaadmahmood**
Ticket: https://mattermost.atlassian.net/browse/MM-17864

Screenshot:
Screenshot 2019-08-29 at 6 49 08 PM

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@marianunez Not sure how to reproduce that, but does not seem to be happening now.
Screenshot 2019-08-29 at 7 23 53 PM
Screenshot 2019-08-29 at 7 24 21 PM

**Comment by hanzei** [comment]
@asaadmahmood What do you think about adding a line break after the title? It's kind of weird to have the labels directly next to the title.

**Comment by asaadmahmood** [comment]
@hanzei I agree. Pushed an update.
Screenshot 2019-08-29 at 11 52 55 PM

**Comment by lindalumitchell** [comment]
I don't have edit permission in this repo to remove the QA Review label. Can someone else help remove it please?

**Pull request merged**
