### PR TITLE
Bump version to 2.1.7

### PR DESCRIPTION
**Pull request by avas27JTG**
#### Summary
- https://github.com/mattermost/mattermost-plugin-github/pull/697

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM, but I would love to see a 2.2.0 soon as a lot of changes have accumulated in `master`

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@hanzei @DHaussermann I'm wondering your thoughts on if we need a release test on this, besides the step we recently added to ensure the build runs properly on a Cloud server. cc @AayushChaudhary0001

**Comment by hanzei** [comment]
I'm fine with skipping release testing on this one.

**Comment by avas27JTG** [comment]
> I'm fine with skipping release testing on this one.

Cool, I'll add the QA to the pipeline and we can do it whenever we get available bandwidth

**Comment by mickmister** [comment]
> Cool, I'll add the QA to the pipeline and we can do it whenever we get available bandwidth

@avas27JTG I'm not sure exactly what this means. Do you mean specifically my comment about "the step we recently added to ensure the build runs properly on a Cloud server"?

**Comment by avas27JTG** [comment]
> > Cool, I'll add the QA to the pipeline and we can do it whenever we get available bandwidth
> 
> @avas27JTG I'm not sure exactly what this means. Do you mean specifically my comment about "the step we recently added to ensure the build runs properly on a Cloud server"?

@mickmister I meant that once we are sure that it runs properly on cloud server we can perform a QA sanity to proceed with the actual release following point #5 `Perform release testing` of the release process.
Please let me know if we want to skip QA sanity and just cut the actual release if it works well on Cloud Server.

**Comment by mickmister** [comment]
@avas27JTG I've confirmed this runs correctly on a Cloud server. Merging the PR since the change is minuscule

**Pull request merged**
