### PR TITLE
make Github icon url configurable

### PR DESCRIPTION
**Pull request by zetaab**
I installed 0.8 version today our mattermost, and now the problem is that Icon is not visible at all. This is because icon url is hardcoded to code, and our mattermost server cannot access to internet.

That is why I suggest that we make this url configurable

### CODE REVIEW

**Comment by zetaab** [comment]
I have no idea why that test fails

**Comment by lieut-data** [comment]
Is there a way we could have the plugin host the image itself? Or for the client-side code to embed the image into the webpack bundle directly? 

Presumably this doesn't need to actually be "configurable", but just accessible without an internet connection. Or, @zetaab, were you hoping to allow changing it from the default logo?

**Comment by zetaab** [comment]
Yes I hope that i could change the url of the logo. This code works fine for me. I am now hosting that same image inside our internal network and it works fine. This feature also allows changing the bot icon if someone wants customize it

**Comment by jwilander** [comment]
I do have a PR here for self-hosting the image from the plugin https://github.com/mattermost/mattermost-plugin-github/pull/50

However, I'm not opposed to making it configurable

**Comment by crspeller** [comment]
Agree with @jasonblais https://github.com/mattermost/mattermost-plugin-github/pull/50 is the solution to this. Thanks for the contribution, but going to close this.

**Pull request closed without merging**
