### PR TITLE
Release 2.1.3

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-github/pull/586
- https://github.com/mattermost/mattermost-plugin-github/pull/590

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-github/issues/588

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
Do we really need a patch release? Can we stick with https://github.com/mattermost/mattermost-plugin-github/pull/583?

**Comment by mickmister** [comment]
@hanzei The idea was to get this fix on community sooner, but I'm up for using the existing release cc @DHaussermann

**Comment by hanzei** [comment]
Do we need a fix on Community soon, given that https://github.com/mattermost/mattermost-webapp/pull/11232 was merged?

**Comment by DHaussermann** [comment]
@mickmister Do we still want to proceed with this release given the react changes in the last few days?

**Review by hanzei — CHANGES_REQUESTED** [review]
We need the linter fixes

**Comment by mickmister** [comment]
@hanzei Merging since the linting fixes here are all `ioutil -> io` and `errors.Errorf -> errors.New`

**Pull request merged**
