### PR TITLE
Extend githubPermalinkRegex

### PR DESCRIPTION
**Pull request by doc-sheet**
#### Summary
Turns out `.` (dot) is a valid character for github repo name.
I couldn't find official info on what other characters are allowed there.

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Good catch, thanks for the fix :+1:

**Review by javaguirre — APPROVED** [review]
LGTM!

**Review by javaguirre — APPROVED** [review]

**Comment by hanzei** [comment]
@doc-sheet Would you mind signing the CLA? Please let me know if you have any questions.

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder to review the PR

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Good catch! I can now use plugins that has a `. ` in the name

Briefly regression tested subscription creation to various other repos including more common character like `hello-world`.  No issues found.  

LGTM!

Thanks @doc-sheet  fir the fix!

**Pull request merged**
