### PR TITLE
Require read:org scope for OAuth connect

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost-plugin-github/pull/154 did add a feature flag `--exclude-org-member` to subscriptions, which allows to ignore events from organization members. Currently, the oauth scope doesn't include information about the membership of the user. This PR fixes it by broadening the scope.

To apply this fix to a given subscription the user who created it has to disconnect and reconnect the MM account to GitHub.

I've tested my changes with ngrok and a test organisation.

#### QA test steps
1. Create two users and connect them both to the github via `github connect`
2. Create an organization ORG and let both users join it
3. Make sure organization visibility is set to "private" for user B
4. As user A create a subscription to ORG using `--exclude-org-member`
5. As user B create an issue to trigger the subscription
6. Confirm no notification is shown in MM

@DHaussermann If you need help testing this, just let me know.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/199

### CODE REVIEW

**Comment by DHaussermann** [comment]
@hanzei I'm not quite understanding this problem.  When you say 

> Create two users and connect them both to the github oauth app

Is the issue that users who log into GutHub and make changes while not connected in Mattermost are not affected by the `--exclude-org-member` functionality?

**Comment by hanzei** [comment]
@DHaussermann Does
> Create two users and connect them both to the github via `github connect`

make it more clear?

**Comment by DHaussermann** [comment]
@hanzei No, to clairify my comment above, the problem is not that I don't understand the instructions. I don't understand which users are affected by the issue and which one are not. 

I can do this and test. But, my concern is that I don't see how this differs form the testing done before that did not catch this issue. (I always connect the test users in this way.) Maybe a test user was authenticated in GitHub and not mapped in Mattermost at the time when I tested initially?

**Comment by DHaussermann** [comment]
@hanzei you can disregards this question. ☝️   I'm not having any issues reproducing it. In fact, I'm having a hard time making the flag work now to exclude anyone. 
I'm looking into it.

**Comment by DHaussermann** [comment]
@hanzei I can't make this exclude flag work at all. Maybe we can follow up?

**Comment by DHaussermann** [comment]
Hi @hanzei as we discuss, I'm not seeing the `--exclude-org-member` I have tried to isolate this with new data. In did the folllwing;
- Setup new MM server
- Build GitHub plugin form this branch and install
- Create a new application in my Organization
- Configure the plugin to run with the new App
- Login as the owner, connect to GitHub and Grant access to the app    
- Create a subscription that includes the `--exclude-org-member` flag
As several users who are publicly members of the ORG, perform actions that trigger events to be delivered 
**Observed** Events are still delivered  

I feel like you where on the correct track by seeing what set of permissions are set when you `Grant` but I'm not seeing how to verify this.

**Comment by hanzei** [comment]
@DHaussermann Could you double check that you have set a organisation in settings? Otherwise `--exclude-org-member` has to effect.
Screenshot from 2020-03-19 13-49-46

**Comment by DHaussermann** [comment]
> Could you double check that you have set a organisation in settings? Otherwise --exclude-org-member has to effect.

Thanks @hanzei this was the problem! (on both servers I tried) I did add an issue https://github.com/mattermost/mattermost-plugin-github/issues/214 to validate against this.

**Pull request merged**
