### PR TITLE
[MM-61118] Add diagnostics data to the Support Packet

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
When a Support Packet gets generated, the plugin now includes diagnostics data via a `diagnostics.yaml` file into the Packet.

Example content of `github/diagnostics.yaml`:

```yaml
version: 2.3.0+6ba0bcd
connected_user_count: 1
is_oauth_configured: true
```

Requires https://github.com/mattermost/mattermost/pull/28833 on the server side.

See https://mattermost.atlassian.net/wiki/spaces/CLOUD/pages/3083108354/Diagnostics+data+from+Core+Plugins+to+the+Support+Packet for more context.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61119

### CODE REVIEW

**Comment by hanzei** [comment]
@wiggin77 @Kshitij-Katiyar Gentle reminder to review the PR :wink:

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
@AayushChaudhary0001 Can you please review the PR? QA steps are in the ticket. Let me know if you need anything from me.

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by hanzei** [comment]
Per discussion with @raghavaggarwal2308, QA testing will happen post-merge.

**Pull request merged**
