### PR TITLE
Connect to private repositories by default

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary

- Added the feature to connect to private repositories by slash command without explicitly mentioning `private`
- Added a setting in the plugin to enable/disable this feature

#### Screenshots

image

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM. Thanks for the addition :+1:

**Review by larkox — APPROVED** [review]
LGTM. Thanks!

**Comment by manojmalik20** [comment]
Friendly ping @DHaussermann for review.

**Comment by DHaussermann** [comment]
Very sorry for the delay on this @manojmalik20 I should finally be abe to get to this today 👍

**Comment by DHaussermann** [comment]
@hanzei  or @larkox  are you able to pull `master` into this PR branch?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- `Connect to private Repositories by default` functions as expected with no need to append `private`
- When enabled the redundant `private` parameter is removed from the auto complete as expected
- Flag to enable / disable this feature works as expected
- Flag is `false` by default to ensure seamless upgrade
- Tested  on desktop and browser

LGTM! 

Huge thanks @manojmalik20 for this enhancement.

**Pull request merged**
