### PR TITLE
Make apply

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Run `make apply`

#### Ticket Link
Follow up on https://github.com/mattermost/mattermost-plugin-github/pull/417

### CODE REVIEW

**Comment by hanzei** [comment]
@justinegeffen Heads up that after all changes in `plugin.json` `make apply` need to be run on a local clone and they generated files need to get committed. I forgot to tell you about that in the PR.

**Comment by justinegeffen** [comment]
So I need to clone the repos I updated, run ``make apply`` on master, and then commit the changes? I updated numerous repos so I'm guessing they all need to be updated like that?

**Comment by hanzei** [comment]
@justinegeffen Let me take care of update the repos that need an update. I should have told you that this a step that needs to be done. I've filled https://mattermost.atlassian.net/browse/MM-32703 to add an automated check which will prevent this issue from happening in the future.

**Comment by hanzei** [comment]
Merging to fix `master`.

**Review by iomodo — APPROVED** [review]

**Pull request merged**
