### PR TITLE
Fixed formatting error

### PR DESCRIPTION
**Pull request by Akito13**
Cleared up very tiny but at the same time very confusing formatting error.

### CODE REVIEW

**Comment by lieut-data** [comment]
Thanks, @Akito13! Can I get your help to sign the CLA so we can merge this excellent improvement?

**Comment by Akito13** [comment]
> 
> 
> Thanks, @Akito13! Can I get your help to sign the CLA so we can merge this excellent improvement?

I submitted my information on the survey link, but I found the process a little confusing, counting in all factors for signing the CLA. Do I need to do anything else except what I have already done? Maybe there is an even easier way to sign the CLA, than I have seen so far.

**Comment by jasonblais** [comment]
@Akito13 You should be all set with respect to the CLA. I'm curious if you'd be open to sharing more about the CLA process and how it was for you, as we always look to improve the contributor experience.

**Comment by Akito13** [comment]
> 
> 
> @Akito13 You should be all set with respect to the CLA. I'm curious if you'd be open to sharing more about the CLA process and how it was for you, as we always look to improve the contributor experience.

Sure, I will gladly accept your offer. I will take some time to recreate the CLA signing process tomorrow at some time.

**Pull request merged**
