### PR TITLE
Release v2.0.0-rc2

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This should be the final rc. All bugs found on community have been fixed. Let's push this out to community and check if any new issues pop up.

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-github/issues/304

### CODE REVIEW

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-github/pull/366  needs to be merged first.

**Comment by hanzei** [comment]
Heads up: I've just submitted https://github.com/mattermost/mattermost-plugin-github/pull/376. Let's wait for that one to get merged.

**Comment by hanzei** [comment]
@DHaussermann @jfrerich This is ready for review

**Comment by hanzei** [comment]
@DHaussermann @jfrerich Could you please review this PR? I would like to push a final rc out ASAP.

**Review by jfrerich — APPROVED** [review]
LGMT, @hanzei!

**Comment by DHaussermann** [comment]
@hanzei I have now completed all GitHub release tests. Couple point for youy:
1. The only new issue I have found is https://github.com/mattermost/mattermost-plugin-github/issues/386 which pertains to the new mute functionality. Please confirm if this issue can be resolved in future release.
2. How to we proceed to get the correct version number now? My understanding is that we are now ready for v2.0.0 release

**Review by DHaussermann — APPROVED** [review]

**Comment by hanzei** [comment]
> How to we proceed to get the correct version number now? My understanding is that we are now ready for v2.0.0 release

I want to cut v2.0.0-rc2 to do a final test on community. While that is happening on I'm going to prepare the actually `v2.0.0` release.

**Pull request merged**
