### PR TITLE
Include comments in notifications for approval / changes requested

### PR DESCRIPTION
**Pull request by enolal826**
Fix https://github.com/mattermost/mattermost-plugin-github/issues/152

It's my first contribution, so even though it's not too complex, any comment would be appreciated.

Thanks!

### CODE REVIEW

**Comment by mickmister** [comment]
LGTM, great job @enolal826!

**Comment by hanzei** [comment]
@enolal826 Would you please merge `master` into your branch?

**Comment by enolal826** [comment]
Done, thanks!

**Pull request merged**
