### PR TITLE
[MM-42918] Add debug information for setup wizard

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
I'm unable to reproduce the issue linked in the ticket.

To debug the issue if it occurs again, I've added debug information on why exactly the wizard didn't run.

If the PR gets approved, I'm going to copy the change into https://github.com/mattermost/mattermost-plugin-gitlab.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42918

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@hanzei What are the requirements to get this merged?

**Comment by hanzei** [comment]
@mickmister Good question. In order to test this PR, one has to jump through a couple of hoops, namely removing the signature check for the plugin so this build can be installed as part of the onboarding flow.

Once that is done, the PR can be tested. It produces output like this one:
`debug [2023-05-22 23:19:30.590 +02:00] OAuth is configured, skipping setup wizard    caller="app/plugin_api.go:970" plugin_id=github GitHubOAuthClientID="***8cb3" GitHubOAuthClientSecret="***3d78" UsePreregisteredApplication=false
`

To me that is enough testing given the complex steps to get there. Are you fine with emerging the PR as it is?

**Comment by hanzei** [comment]
GitLab PR: https://github.com/mattermost/mattermost-plugin-gitlab/pull/379

**Comment by mickmister** [comment]
> To me that is enough testing given the complex steps to get there. Are you fine with emerging the PR as it is?

LGTM :+1:

**Pull request merged**
