### PR TITLE
Avoided panic on empty body of PR and Issue

### PR DESCRIPTION
**Pull request by abdulsmapara**
#### Summary

- Checks whether pointer to the body of PR/Issue is `nil` before accessing it to avoid panic.
- I have assumed that `result` obtained by calling `Get()` on PR/Issue is never `nil` as other functions do not check this condition (Reference: https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/api.go#L489).

#### Ticket Link

Extension to the PR https://github.com/mattermost/mattermost-plugin-github/pull/326 that fixes https://github.com/mattermost/mattermost-plugin-github/issues/312

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann I'm happy to review this one myself, given that I also found the bug.

**Comment by DHaussermann** [comment]
@hanzei or @larkox If you have a bit of time, could one of you peer-test this PR using the  peer testing process documented here https://mattermost.atlassian.net/wiki/spaces/INT/pages/619937892/Peer+Testing+Process

**Comment by hanzei** [comment]
@DHaussermann :poi

**Comment by DHaussermann** [comment]
Thanks for testing @hanzei. Follow-up on this So I can make sure there is appropriate release testing in place. How is it possible to create a PR where `Body` is empty i.e. `nil`? 
I have tested with and an empty description field but this is different?

**Comment by hanzei** [comment]
@DHaussermann E.g. https://github.com/mattermost/mattermost-plugin-demo/pull/112 is a PR without a description, which would cause a panic. I haven't found an issue to reproduce the issue for far.

**Pull request merged**
