### PR TITLE
Log post when CreatePost fails

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
`CreatePost` should never fail. This PR adds the post to the log output. It doesn't look pretty, as it's a plain go struct dump (Post don't have a `String()` method), but for debugging it does the trick.

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-github/issues/405

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann I'm not sure if there is much to QA review here. These error cases are neither mockable nor triggerable within the Server. Would you be find merging this PR without QA review?

**Comment by DHaussermann** [comment]
Sorry I missed this ping @hanzei. Sounds reasonable to me.

**Review by DHaussermann — APPROVED** [review]
No functional testing applicable here. Please merge. 

LGTM!

**Pull request merged**
