### PR TITLE
Use pluginID instead of Hardcoded "github" string

### PR DESCRIPTION
**Pull request by chetanyakan**

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
LGTM!  Thanks, @chetanyakan!

**Review by hanzei — APPROVED** [review]
LGMT :+1:

**Comment by hanzei** [comment]
@DHaussermann A general smoke test should be enough

**Comment by hanzei** [comment]
I did some smoke testing around connecting and disconnect and didn't found any issues. This is good to merge once v2.0.0 is cut.

**Pull request merged**
