### PR TITLE
Bump version to 2.2.0.

### PR DESCRIPTION
**Pull request by avas27JTG**
#### Summary
- https://github.com/mattermost/mattermost-plugin-github/issues/470
- https://github.com/mattermost/mattermost-plugin-github/pull/606
- https://github.com/mattermost/mattermost-plugin-github/pull/628
- https://github.com/mattermost/mattermost-plugin-github/pull/598
- https://github.com/mattermost/mattermost-plugin-github/issues/500
- https://github.com/mattermost/mattermost-plugin-github/pull/462
- https://github.com/mattermost/mattermost-plugin-github/issues/558
- https://github.com/mattermost/mattermost-plugin-github/pull/656
- https://github.com/mattermost/mattermost-plugin-github/issues/548
- https://github.com/mattermost/mattermost-plugin-github/pull/648
- https://github.com/mattermost/mattermost-plugin-github/pull/671
- https://github.com/mattermost/mattermost-plugin-github/pull/679
- https://github.com/mattermost/mattermost-plugin-github/issues/613
- https://github.com/mattermost/mattermost-plugin-github/pull/690
- https://github.com/mattermost/mattermost-plugin-github/issues/686
- https://github.com/mattermost/mattermost-plugin-github/pull/700
- https://github.com/mattermost/mattermost-plugin-github/pull/683
- https://github.com/mattermost/mattermost-plugin-github/pull/661
- https://github.com/mattermost/mattermost-plugin-github/pull/664
- https://github.com/mattermost/mattermost-plugin-github/pull/699
- https://github.com/mattermost/mattermost-plugin-github/pull/712
- https://github.com/mattermost/mattermost-plugin-github/pull/718
- https://github.com/mattermost/mattermost-plugin-github/pull/729
- https://github.com/mattermost/mattermost-plugin-github/pull/735

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Can we get the open PRs that only require QA review into this release?

- https://github.com/mattermost/mattermost-plugin-github/pull/683
- https://github.com/mattermost/mattermost-plugin-github/pull/661
- https://github.com/mattermost/mattermost-plugin-github/pull/664
- https://github.com/mattermost/mattermost-plugin-github/pull/699

**Comment by avas27JTG** [comment]
> Can we get the open PRs that only require QA review into this release?
> 
> * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)

Sure, let me look

**Comment by avas27JTG** [comment]
> > Can we get the open PRs that only require QA review into this release?
> > 
> > * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> > * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> > * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> > * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)
> 
> Sure, let me look

@hanzei I added them to this release milestone, and the QA will start testing these issues, after which we can merge them into the master.

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved
All the changes merged are working fine, LGTM.

**Comment by avas27JTG** [comment]
> > > Can we get the open PRs that only require QA review into this release?
> > > 
> > > * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> > > * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> > > * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> > > * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)
> > 
> > 
> > Sure, let me look
> 
> @hanzei I added them to this release milestone, and the QA will start testing these issues, after which we can merge them into the master.



> > > Can we get the open PRs that only require QA review into this release?
> > > 
> > > * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> > > * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> > > * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> > > * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)
> > 
> > 
> > Sure, let me look
> 
> @hanzei I added them to this release milestone, and the QA will start testing these issues, after which we can merge them into the master.



> > > Can we get the open PRs that only require QA review into this release?
> > > 
> > > * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> > > * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> > > * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> > > * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)
> > 
> > 
> > Sure, let me look
> 
> @hanzei I added them to this release milestone, and the QA will start testing these issues, after which we can merge them into the master.



> > > Can we get the open PRs that only require QA review into this release?
> > > 
> > > * [[GH-418]: Fixed issue #418 'Added --exclude option to subscriptions command'. #683](https://github.com/mattermost/mattermost-plugin-github/pull/683)
> > > * [[GH-512,513] Fixed issue #512 and #513 on github plugin 'Updated subscription success messages' #661](https://github.com/mattermost/mattermost-plugin-github/pull/661)
> > > * [[GH-378]:Fixed issue #378 'Check for webhook while subscribing' #664](https://github.com/mattermost/mattermost-plugin-github/pull/664)
> > > * [[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command #699](https://github.com/mattermost/mattermost-plugin-github/pull/699)
> > 
> > 
> > Sure, let me look
> 
> @hanzei I added them to this release milestone, and the QA will start testing these issues, after which we can merge them into the master.

@hanzei can you please approve the PR if it looks good to you?

**Comment by avas27JTG** [comment]
@mickmister `min_server_version` is changed to `7.1.0` in this PR https://github.com/mattermost/mattermost-plugin-github/pull/598 so, should we still keep this release as `v2.2.0` or change it to `v3.0.0`?.

**Comment by mickmister** [comment]
@avas27JTG I'm genuinely not sure if bumping the min server version constitutes a new major version of the plugin. We haven't done that in the past.

I'm thinking no, because the main reason we do major version changes is so that the admin is aware of breaking changes. In this case, the only side effect is they just won't be able to upgrade if they are on an older server version. There's not really a breaking change in that regard.

**Review by mickmister — APPROVED** [review]

**Comment by avas27JTG** [comment]
> @avas27JTG I'm genuinely not sure if bumping the min server version constitutes a new major version of the plugin. We haven't done that in the past.
> 
> I'm thinking no, because the main reason we do major version changes is so that the admin is aware of breaking changes. In this case, the only side effect is they just won't be able to upgrade if they are on an older server version. There's not really a breaking change in that regard.

Makes sense, thanks @mickmister we will keep it as a minor release.

**Review by hanzei — APPROVED** [review]
I would like (1/5) to get https://github.com/mattermost/mattermost-plugin-github/pull/712 into the release, but I'm fine with releasing the code as it is.

**Comment by avas27JTG** [comment]
> I would like (1/5) to get #712 into the release, but I'm fine with releasing the code as it is.

Yes, we have planned to include it here, this is in QA review currently.

**Comment by avas27JTG** [comment]
@mickmister @hanzei #712 and #718 are now included.

**Comment by hanzei** [comment]
@avas27JTG @AayushChaudhary0001 Are we good to merge the PR and cut the release?

**Comment by mickmister** [comment]
@hanzei I created an RC build and requested to be installed on community https://community.mattermost.com/core/pl/zd4h5ifbtjngbmi8d87we3x5wa

**Comment by mickmister** [comment]
@avas27JTG @raghavaggarwal2308 Are there any recent changes to the master branch that we _don't_ want to include in this release? Wondering if we can get this in there https://github.com/mattermost/mattermost-plugin-github/pull/729. Let me know, and I'll cut another RC with the latest changes

**Comment by raghavaggarwal2308** [comment]
> Are there any recent changes to the master branch that we don't want to include in this release?

@mickmister No I think we can cut the RC with latest changes. We have just merged the changes for description issue and `see more` link in the tooltip after our last RC (https://github.com/mattermost/mattermost-plugin-github/pull/735).

**Comment by mickmister** [comment]
@raghavaggarwal2308 Can you please merge the into this branch to get https://github.com/mattermost/mattermost-plugin-github/pull/729 into the release?

**Comment by hanzei** [comment]
@mickmister Are we good to cut the release? Is there anything blocking it?

**Comment by mickmister** [comment]
@hanzei Yes I think we're good to go. We've had [36e72f4](https://github.com/mattermost/mattermost-plugin-github/pull/709/commits/36e72f47bfbf10d6631e6f479a5e7d5c49568bbc) running on community for a bit now, and only a few changes/fixes have been added since then.

**Pull request merged**
