### PR TITLE
[GH-219] After creating issue, reply to post in MM with the Github link

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Note this PR is for the create-issue Feature branch, not master.

This ticket adds a response post to a thread if a GitHub issue is created from the post.

image

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-github/issues/219

### CODE REVIEW

**Comment by jfrerich** [comment]
CI linting error PR is here https://github.com/mattermost/mattermost-plugin-github/pull/221

**Comment by levb** [comment]
Removed the QA Review since it's a feature-branch PR.

**Comment by jfrerich** [comment]
> Is there a reasonable way for us to add tests for this kind of functionality in the GitHub plugin?

I don't see a reason why we cannot add tests for this functionality.  Currently, there are no tests for the api layer.  I will create as another ticket and add to the 0.15.0 milestone for tracking. There are 5 other tickets for this feature and I am going to work on those next.  This was the first of 6.

**Pull request merged**
