### PR TITLE
Added extra debug logs to diagnose an issue on community

### PR DESCRIPTION
**Pull request by levb**
DEBUGGING, DO NOT MERGE

### CODE REVIEW

**Comment by jwilander** [comment]
Will this get us the user ID for the panic generated here: https://github.com/mattermost/mattermost-plugin-api/blob/v0.0.26/post.go#L309 ?

**Comment by jwilander** [comment]
Which is called from https://github.com/mattermost/mattermost-plugin-github/blob/v2.1.1/server/plugin/plugin.go#L291

**Comment by levb** [comment]
@jwilander https://github.com/mattermost/mattermost-plugin-api/tree/lev-extra-logging and updated `go.mod`; good catch!

**Comment by levb** [comment]
See https://github.com/mattermost/mattermost-plugin-api/compare/lev-extra-logging?expand=1 for pluginapi

**Pull request closed without merging**
