### PR TITLE
Fix missing PR notifications when using both pulls_created and pulls_merged features filter

### PR DESCRIPTION
**Pull request by verdel**
#### Summary

There is currently a bug described in the linked issue below. If both `pulls_created` and `pulls_merged` features are set for a subscription, any type of PR events are ignored.

I have fixed the `if` statement, and now it is possible to use both values and receive notifications for the respective event types.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-github/issues/826

### CODE REVIEW

**Comment by wiggin77** [comment]
Thanks @verdel

**Review by raghavaggarwal2308 — APPROVED** [review]
LGTM, Thanks for the contribution @verdel

**Comment by verdel** [comment]
> LGTM, Thanks for the contribution @verdel

Thank you for taking the time to review my PR

**Review by wiggin77 — APPROVED** [review]

**Comment by raghavaggarwal2308** [comment]
@verdel This PR is pending for QA review. We will try to get that dine ASAP.

**Comment by verdel** [comment]
Yes, I apologize, I didn't notice the label on the PR. Thank you.

**Review by AayushChaudhary0001 — APPROVED** [review]
This PR has been tested for both, pull request created and requests merged. The user is provided the notification for both the events if the subscriptions are created for both of them and any one event is triggered, LGTM. Approved.

**Comment by raghavaggarwal2308** [comment]
Merging this PR now, thanks for the contribution! @verdel

**Pull request merged**
