### PR TITLE
Replace `option.label` with `option.value` to be consistent

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

Fixes: #263

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
Thanks for the quick fix @haardikdharma10 :+1:

**Comment by haardikdharma10** [comment]
cc @mickmister, awaiting your quick look onto this :)

**Comment by jasonblais** [comment]
@hanzei is there someone else who can do a second dev review while Michael is away?

**Comment by hanzei** [comment]
Sure. @larkox can you help out?

**Review by larkox — APPROVED** [review]

**Comment by haardikdharma10** [comment]
@DHaussermann need your quick look onto this.

**Comment by DHaussermann** [comment]
Sorry @haardikdharma10 your PR does not seem to be testable right now. I was seeing some regressions in the modals and when I looked at the `master` branch it seems there is already a bug blocking testing. 

I have created https://github.com/mattermost/mattermost-plugin-github/issues/451 to address this.

**Review by mickmister — CHANGES_REQUESTED** [review]
Hi @haardikdharma10! I looked through the codebase and found another usage of `option.label` in [webapp/src/components/react_select_setting.jsx](https://github.com/mattermost/mattermost-plugin-github/blob/bc8056eb5ce1ee9ae673c33d999a38a77e538183/webapp/src/components/react_select_setting.jsx#L65-L67):

https://github.com/mattermost/mattermost-plugin-github/blob/bc8056eb5ce1ee9ae673c33d999a38a77e538183/webapp/src/components/react_select_setting.jsx#L65-L67

This should also be changed to use `option.value`, to solve the issue of using `option.label` as the option's unique identifier

**Comment by haardikdharma10** [comment]
> Hi @haardikdharma10!
> 
> I looked through the codebase and found another usage of `option.label` (though it is `value.label` here) in [webapp/src/components/react_select_setting.jsx](https://github.com/mattermost/mattermost-plugin-github/blob/bc8056eb5ce1ee9ae673c33d999a38a77e538183/webapp/src/components/react_select_setting.jsx#L65-L67):
> 
> https://github.com/mattermost/mattermost-plugin-github/blob/bc8056eb5ce1ee9ae673c33d999a38a77e538183/webapp/src/components/react_select_setting.jsx#L65-L67
> 
> This should also be changed to use `option.value`, to solve the issue of using `option.label` as the option's unique identifier

Thanks for taking a look @mickmister. I'll have to change that to `value.value` right?

**Comment by mickmister** [comment]
> Thanks for taking a look @mickmister. I'll have to change that to `value.value` right?

@haardikdharma10 That's correct 🙂

**Comment by haardikdharma10** [comment]
> > Thanks for taking a look @mickmister. I'll have to change that to `value.value` right?
> 
> @haardikdharma10 That's correct 🙂

Perfect! I have pushed the changes.

**Review by mickmister — APPROVED** [review]
LGTM :+1:  Thanks @haardikdharma10!

**Comment by DHaussermann** [comment]
Hi @haardikdharma10 I'm seeing an issue when I try selecting a repo from the drop down. I see a permission related error in the console and then a 401 response. 
This is occurring for both public and private repos. Just to be sure, I did disconnect and reconnect my user and still saw the same issue occur. 
The Attach functionality does not seem affected just the create functionality.   

image
image

Steps:
- Deploy this PR
- Connect a user to GitHub
- Make a post
- Click the `...` menu and select the option to create a GitHub issue
- Once the modal open open the browser dev console 
- Open the repo drop down and select any option
**Observed** Console error occur and selection did not take

As far as  I know, the issues with repo selection should have been resolved with the last merge up from `master`. Can you please check if you can reproduce this?

**Comment by DHaussermann** [comment]
@haardikdharma10 I believe the issue found has to be investigated before the next round of testing.
I'm adding the label for awaiting submitter action. Please reach out if I've misunderstood something.

**Comment by mickmister** [comment]
@DHaussermann Maybe this is fixed now `master` is merged with this branch

**Comment by haardikdharma10** [comment]
Thanks @mickmister! Can you also remove the `Awaiting Submitter Action` label? Sorry for the trouble, I don't have the necessary permissions to do that 🙂

**Comment by dipak-demansol** [comment]
need to discuss with developer, i will test it on Monday.

**Comment by dipak-demansol** [comment]
i tested, 
:- i was able to selecting a repo from the drop down. and successfully created a GitHub issue, bug while creating a issue in the Assignees input box there was only 1 developer name i was getting and

**Comment by dipak-demansol** [comment]
i tested, 
:- i was able to select a repo from the drop down.
:- i successfully created a GitHub issue.
          but while creating a issue, in the Assignees dropdown there is only My name in the list, and in the Milestone dropdown there is no data so i'm not sure about its pass or fail.

**Comment by jasonblais** [comment]
cc @DHaussermann on above

**Comment by DHaussermann** [comment]
Discussed with @dipak-demansol today. After a quick look at the attach modal as a precaution this would be good to merge.

**Comment by hanzei** [comment]
@dipak-demansol Did you got the time to look into this issue yet?

**Comment by dipak-demansol** [comment]
> @dipak-demansol Did you got the time to look into this issue yet?
i will do it today.

**Comment by dipak-demansol** [comment]
@hanzei @DHaussermann LGTM.

**Pull request merged**
