### PR TITLE
Release bump v2.2.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-github/pull/534
- https://github.com/mattermost/mattermost-plugin-github/pull/633
- https://github.com/mattermost/mattermost-plugin-github/pull/462
- https://github.com/mattermost/mattermost-plugin-github/pull/600
- https://github.com/mattermost/mattermost-plugin-github/pull/596
- https://github.com/mattermost/mattermost-plugin-github/pull/632
- https://github.com/mattermost/mattermost-plugin-github/pull/644
- https://github.com/mattermost/mattermost-plugin-github/pull/598
- https://github.com/mattermost/mattermost-plugin-github/pull/628

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-github/issues/582

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
I'm not against releasing a new version with so little changes, but I'm wondering if it's worth in terms of QA resources.

**Comment by mickmister** [comment]
@hanzei I agree. The reason I'm wanting this released is because I'm wanting to set up an org-wide webhook in the Contributors channel. This feature will allow us to make the posts less noisy. @DHaussermann Thoughts on releasing an RC version to community?

**Pull request closed without merging**
