### PR TITLE
Bump version to v1.0.0

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Bumps the version to `v.1.0.0`

### CODE REVIEW

**Comment by jfrerich** [comment]
> Blocking until #252 and #252 have been merged.

@hanzei you linked 252 twice.  Which is the other PR you would like to merge before merging this ticket?

**Comment by levb** [comment]
@hanzei https://github.com/mattermost/mattermost-plugin-github/pull/258, which I think was one of the 2 you wanted to wait for has been merged. The other one, https://github.com/mattermost/mattermost-plugin-github/pull/252 seems like has no functional changes and a considerable refactor, so should probably require a QA pass.

Should we push #252 out into, say, a 1.0.1?

**Comment by levb** [comment]
@DHaussermann @hanzei are we just waiting on QA now for 1.0?

**Comment by DHaussermann** [comment]
@levb end to end testing was done a couple days ago. I did want to approve until all issues filed had been triaged to ensure nothing more was needed for 1.0.0. I also had to investigate this https://github.com/mattermost/mattermost-plugin-github/issues/286

I would sat we're good to ship now.

**Pull request merged**
