### PR TITLE
Run Playwright Test on pull requests

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
Run Playwright tests on each pull request so that tests are run before merging PRs.

#### Ticket Link
NONE

### CODE REVIEW

**Comment by wiggin77** [comment]
Looks like Playwright tests have been disabled a long time, and are completely broken.

**Comment by fmartingr** [comment]
Do we want to enable this as-is or are tests going to be fixed before enabling this pipeline step?

**Comment by wiggin77** [comment]
> Do we want to enable this as-is or are tests going to be fixed before enabling this pipeline step?

No point enabling it now. It is too far broken to make a quick fix.

**Comment by wiggin77** [comment]
We will revisit this at a later date.

**Pull request closed without merging**
