### PR TITLE
MM-21246 - Updating github icon positioning

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-21246 - Updating github icon positioning
Can someone also test if the styles are applied? I don't have github running so wasn't able to test that.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21246

### CODE REVIEW

**Comment by DHaussermann** [comment]
@asaadmahmood - I believe this was already resolved by https://github.com/mattermost/mattermost-plugin-github/pull/162

Latter rounds of testing showed the issue as resolved for me. Please advise. In the future, I will update the corresponding Jira task when this happens.

**Comment by asaadmahmood** [comment]
@DHaussermann Specific to Github, can you show me a screenshot of how the Github icon looks with that other change?

**Comment by DHaussermann** [comment]
Yup, here you go ...

GitHub-Icon


Please let me know if you see the need for any further changes.

**Comment by asaadmahmood** [comment]
Nops, looks good, we can close this PR.

**Pull request closed without merging**
