### PR TITLE
MM-35518 - Add CodeQL check

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
Added step to run automated CodeQL checks. Once this file is merged, the codeql checks (code scanning checks) will automatically be performed on following conditions:
- new pull requests to master branch
- scheduled to run every week once (it automatically pulls the latest codeql checks added, if any)

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-35518

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
Do we really need to add such file into every repo? At least for the plugins that 30+ repos

**Comment by srkgupta** [comment]
> Do we really need to add such file into every repo? At least for the plugins that 30+ repos

Yes, this is a one-time task. The code scanning results will be isolated and tracked per plugin repo.

**Comment by hanzei** [comment]
> > Do we really need to add such file into every repo? At least for the plugins that 30+ repos
> 
> Yes, this is a one-time task. The code scanning results will be isolated and tracked per plugin repo.

What makes your confident that the pipeline will never change?

**Comment by srkgupta** [comment]
> What makes your confident that the pipeline will never change?

It uses the pipeline provided by Github and I don't expect any breaking changes here. There are several repositories which is already utilising this pipeline. Even if there are some changes in the future, Github will most probably ensure that its automatically handled. Worst case, if at all there are breaking changes which requires us to update the codeql-analysis file individually, we might think of automating and push it across all the repos where codeql is enabled.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Pull request merged**
